file = open('day8input.txt')
file_content = file.read()
file.close()

example_input = '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''

day8input = file_content.split('\n')
# day8input = example_input.split('\n')